# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/action/action.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/action/action.proto',
  package='action',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16pb/action/action.proto\x12\x06\x61\x63tion\"\x0e\n\x0c\x45mptyMessage\"l\n\x13RecordActionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12#\n\titem_type\x18\x04 \x01(\x0e\x32\x10.action.ItemType*`\n\x08ItemType\x12\x0c\n\x08SOLUTION\x10\x00\x12\x0f\n\x0bTECH_RESULT\x10\x01\x12\x08\n\x04\x43\x41SE\x10\x02\x12\n\n\x06PATENT\x10\x03\x12\x10\n\x0c\x43OMPANY_NEED\x10\x04\x12\r\n\tCITY_NEED\x10\x05\x32T\n\rActionService\x12\x43\n\x0cRecordAction\x12\x1b.action.RecordActionRequest\x1a\x14.action.EmptyMessage\"\x00\x62\x06proto3'
)

_ITEMTYPE = _descriptor.EnumDescriptor(
  name='ItemType',
  full_name='action.ItemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOLUTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TECH_RESULT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CASE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PATENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPANY_NEED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_NEED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=160,
  serialized_end=256,
)
_sym_db.RegisterEnumDescriptor(_ITEMTYPE)

ItemType = enum_type_wrapper.EnumTypeWrapper(_ITEMTYPE)
SOLUTION = 0
TECH_RESULT = 1
CASE = 2
PATENT = 3
COMPANY_NEED = 4
CITY_NEED = 5



_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='action.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=48,
)


_RECORDACTIONREQUEST = _descriptor.Descriptor(
  name='RecordActionRequest',
  full_name='action.RecordActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='action.RecordActionRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='action.RecordActionRequest.item_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='action.RecordActionRequest.action', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_type', full_name='action.RecordActionRequest.item_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=158,
)

_RECORDACTIONREQUEST.fields_by_name['item_type'].enum_type = _ITEMTYPE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['RecordActionRequest'] = _RECORDACTIONREQUEST
DESCRIPTOR.enum_types_by_name['ItemType'] = _ITEMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'pb.action.action_pb2'
  # @@protoc_insertion_point(class_scope:action.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

RecordActionRequest = _reflection.GeneratedProtocolMessageType('RecordActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECORDACTIONREQUEST,
  '__module__' : 'pb.action.action_pb2'
  # @@protoc_insertion_point(class_scope:action.RecordActionRequest)
  })
_sym_db.RegisterMessage(RecordActionRequest)



_ACTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ActionService',
  full_name='action.ActionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=258,
  serialized_end=342,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecordAction',
    full_name='action.ActionService.RecordAction',
    index=0,
    containing_service=None,
    input_type=_RECORDACTIONREQUEST,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTIONSERVICE)

DESCRIPTOR.services_by_name['ActionService'] = _ACTIONSERVICE

# @@protoc_insertion_point(module_scope)
