# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from pb.item import item_pb2 as pb_dot_item_dot_item__pb2


class ItemServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetItemList = channel.unary_unary(
        '/item.ItemService/GetItemList',
        request_serializer=pb_dot_item_dot_item__pb2.GetItemListRequest.SerializeToString,
        response_deserializer=pb_dot_item_dot_item__pb2.GetItemListReply.FromString,
        )
    self.GetItem = channel.unary_unary(
        '/item.ItemService/GetItem',
        request_serializer=pb_dot_item_dot_item__pb2.GetItemRequest.SerializeToString,
        response_deserializer=pb_dot_item_dot_item__pb2.Item.FromString,
        )


class ItemServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetItemList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetItemList': grpc.unary_unary_rpc_method_handler(
          servicer.GetItemList,
          request_deserializer=pb_dot_item_dot_item__pb2.GetItemListRequest.FromString,
          response_serializer=pb_dot_item_dot_item__pb2.GetItemListReply.SerializeToString,
      ),
      'GetItem': grpc.unary_unary_rpc_method_handler(
          servicer.GetItem,
          request_deserializer=pb_dot_item_dot_item__pb2.GetItemRequest.FromString,
          response_serializer=pb_dot_item_dot_item__pb2.Item.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'item.ItemService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
