# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/item/item.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.common import common_pb2 as pb_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/item/item.proto',
  package='item',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12pb/item/item.proto\x12\x04item\x1a\x16pb/common/common.proto\"\x0e\n\x0c\x45mptyMessage\"X\n\x12GetItemListRequest\x12!\n\titem_type\x18\x01 \x01(\x0e\x32\x0e.item.ItemType\x12\x0c\n\x04page\x18\x02 \x01(\r\x12\x11\n\tpage_size\x18\x03 \x01(\r\"R\n\x10GetItemListReply\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.item.Item\x12#\n\tpage_info\x18\x02 \x01(\x0b\x32\x10.common.PageInfo\"?\n\x0eGetItemRequest\x12!\n\titem_type\x18\x01 \x01(\x0e\x32\x0e.item.ItemType\x12\n\n\x02id\x18\x02 \x01(\t\"X\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x11\n\titem_type\x18\x05 \x01(\t*`\n\x08ItemType\x12\x0c\n\x08SOLUTION\x10\x00\x12\x0f\n\x0bTECH_RESULT\x10\x01\x12\x08\n\x04\x43\x41SE\x10\x02\x12\n\n\x06PATENT\x10\x03\x12\x10\n\x0c\x43OMPANY_NEED\x10\x04\x12\r\n\tCITY_NEED\x10\x05\x32\x7f\n\x0bItemService\x12\x41\n\x0bGetItemList\x12\x18.item.GetItemListRequest\x1a\x16.item.GetItemListReply\"\x00\x12-\n\x07GetItem\x12\x14.item.GetItemRequest\x1a\n.item.Item\"\x00\x62\x06proto3'
  ,
  dependencies=[pb_dot_common_dot_common__pb2.DESCRIPTOR,])

_ITEMTYPE = _descriptor.EnumDescriptor(
  name='ItemType',
  full_name='item.ItemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOLUTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TECH_RESULT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CASE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PATENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPANY_NEED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CITY_NEED', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=397,
  serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_ITEMTYPE)

ItemType = enum_type_wrapper.EnumTypeWrapper(_ITEMTYPE)
SOLUTION = 0
TECH_RESULT = 1
CASE = 2
PATENT = 3
COMPANY_NEED = 4
CITY_NEED = 5



_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='item.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=66,
)


_GETITEMLISTREQUEST = _descriptor.Descriptor(
  name='GetItemListRequest',
  full_name='item.GetItemListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_type', full_name='item.GetItemListRequest.item_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page', full_name='item.GetItemListRequest.page', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='item.GetItemListRequest.page_size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=156,
)


_GETITEMLISTREPLY = _descriptor.Descriptor(
  name='GetItemListReply',
  full_name='item.GetItemListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='item.GetItemListReply.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_info', full_name='item.GetItemListReply.page_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=240,
)


_GETITEMREQUEST = _descriptor.Descriptor(
  name='GetItemRequest',
  full_name='item.GetItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_type', full_name='item.GetItemRequest.item_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='item.GetItemRequest.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=305,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='item.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='item.Item.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='item.Item.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='item.Item.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='item.Item.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_type', full_name='item.Item.item_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=395,
)

_GETITEMLISTREQUEST.fields_by_name['item_type'].enum_type = _ITEMTYPE
_GETITEMLISTREPLY.fields_by_name['items'].message_type = _ITEM
_GETITEMLISTREPLY.fields_by_name['page_info'].message_type = pb_dot_common_dot_common__pb2._PAGEINFO
_GETITEMREQUEST.fields_by_name['item_type'].enum_type = _ITEMTYPE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['GetItemListRequest'] = _GETITEMLISTREQUEST
DESCRIPTOR.message_types_by_name['GetItemListReply'] = _GETITEMLISTREPLY
DESCRIPTOR.message_types_by_name['GetItemRequest'] = _GETITEMREQUEST
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.enum_types_by_name['ItemType'] = _ITEMTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'pb.item.item_pb2'
  # @@protoc_insertion_point(class_scope:item.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

GetItemListRequest = _reflection.GeneratedProtocolMessageType('GetItemListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETITEMLISTREQUEST,
  '__module__' : 'pb.item.item_pb2'
  # @@protoc_insertion_point(class_scope:item.GetItemListRequest)
  })
_sym_db.RegisterMessage(GetItemListRequest)

GetItemListReply = _reflection.GeneratedProtocolMessageType('GetItemListReply', (_message.Message,), {
  'DESCRIPTOR' : _GETITEMLISTREPLY,
  '__module__' : 'pb.item.item_pb2'
  # @@protoc_insertion_point(class_scope:item.GetItemListReply)
  })
_sym_db.RegisterMessage(GetItemListReply)

GetItemRequest = _reflection.GeneratedProtocolMessageType('GetItemRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETITEMREQUEST,
  '__module__' : 'pb.item.item_pb2'
  # @@protoc_insertion_point(class_scope:item.GetItemRequest)
  })
_sym_db.RegisterMessage(GetItemRequest)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'pb.item.item_pb2'
  # @@protoc_insertion_point(class_scope:item.Item)
  })
_sym_db.RegisterMessage(Item)



_ITEMSERVICE = _descriptor.ServiceDescriptor(
  name='ItemService',
  full_name='item.ItemService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=495,
  serialized_end=622,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetItemList',
    full_name='item.ItemService.GetItemList',
    index=0,
    containing_service=None,
    input_type=_GETITEMLISTREQUEST,
    output_type=_GETITEMLISTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetItem',
    full_name='item.ItemService.GetItem',
    index=1,
    containing_service=None,
    input_type=_GETITEMREQUEST,
    output_type=_ITEM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMSERVICE)

DESCRIPTOR.services_by_name['ItemService'] = _ITEMSERVICE

# @@protoc_insertion_point(module_scope)
